(function(){
var STAGES=[["CANDIDATE","Candidate"],["EXECUTING","Executing"],["STRONG_AGENT","Strong Agent"],["REPAIRING","Repairing"],["RETESTING","Retesting"],["READY","Ready"],["ACCEPTED_HARD","Accepted Hard"],["ACCEPTED_MEDIUM","Accepted Medium"]];
var data=null,lastGood=null;
function el(id){return document.getElementById(id)}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])})}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function toast(t){var x=el("toast");x.textContent=t;x.classList.add("show");setTimeout(function(){x.classList.remove("show")},1400)}
function label(k){for(var i=0;i<STAGES.length;i++)if(STAGES[i][0]===k)return STAGES[i][1];return k}
function ist(){var p=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Kolkata",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(new Date()),h=0,m=0;p.forEach(function(x){if(x.type==="hour")h=+x.value;if(x.type==="minute")m=+x.value});return{h:h,m:m}}
function nextWorker(){var ws=(data&&data.automations)||[];if(!ws.length)return{name:"—",delta:0};var t=ist(),cur=t.h*60+t.m,best=null;ws.forEach(function(w){for(var dh=0;dh<2;dh++){var at=((t.h+dh)%24)*60+w.minute;if(dh===1&&t.h===23)at=1440+w.minute;var d=at-cur;if(d>=0&&(!best||d<best.delta))best={name:w.name,delta:d}}});return best||{name:ws[0].name,delta:0}}
function renderAgents(){var n=nextWorker(),h="";(data.automations||[]).forEach(function(a){var on=a.name===n.name;h+='<div class="agent '+(on?'active':'')+'"><span class="node"></span><div class="time">:'+String(a.minute).padStart(2,"0")+'</div><b>'+esc(a.name)+'</b><small>'+esc(a.role)+'</small></div>'});el("agentFlow").innerHTML=h;el("nextWorker").textContent=n.name;el("nextWorkerTime").textContent=n.delta===0?"NOW":"in "+n.delta+"m"}
function renderMetrics(){var c=data.counts||{},s=data.stage_counts||{},target=data.target_tasks||100,a=c.accepted_total_live!=null?c.accepted_total_live:(c.accepted_total||0);el("acceptedRing").textContent=a;el("hardAccepted").textContent=c.accepted_hard_live!=null?c.accepted_hard_live:(c.hard||0);el("mediumAccepted").textContent=c.accepted_medium_live!=null?c.accepted_medium_live:(c.medium||0);el("remaining").textContent=c.remaining_live!=null?c.remaining_live:Math.max(0,target-a);el("ring").style.setProperty("--pct",clamp(a/target*100,0,100)+"%");el("candidateCount").textContent=c.unique_candidates!=null?c.unique_candidates:(data.tasks||[]).length;el("executingCount").textContent=s.EXECUTING||0;el("strongCount").textContent=s.STRONG_AGENT||0;el("repairCount").textContent=s.REPAIRING||0;el("readyCount").textContent=s.READY||0;el("infraCount").textContent=c.execution_infrastructure_error||0;el("version").textContent="V"+(data.benchmark_version||"1.0")}
function fillFilters(){var ts=data.tasks||[],d0=el("domainFilter").value,s0=el("stageFilter").value,ds=[...new Set(ts.map(function(t){return t.domain}).filter(Boolean))].sort();el("domainFilter").innerHTML='<option value="">All domains</option>'+ds.map(function(d){return'<option '+(d===d0?'selected':'')+'>'+esc(d)+'</option>'}).join("");el("stageFilter").innerHTML='<option value="">All stages</option>'+STAGES.map(function(s){return'<option value="'+s[0]+'" '+(s[0]===s0?'selected':'')+'>'+esc(s[1])+'</option>'}).join("")}
function filtered(){var q=el("search").value.toLowerCase().trim(),s=el("stageFilter").value,d=el("domainFilter").value,df=el("difficultyFilter").value;return(data.tasks||[]).filter(function(t){var h=[t.id,t.title,t.domain,t.archetype,t.subdomain].join(" ").toLowerCase();return(!q||h.indexOf(q)>=0)&&(!s||t.stage===s)&&(!d||t.domain===d)&&(!df||t.difficulty===df)})}
function card(t){var p=t.pipeline_summary||{passed:0,total:17,percent:0},f=t.failure_codes||[];return'<article class="task"><button class="open" data-task="'+esc(t.id)+'" aria-label="Open task"></button><div class="task-id">'+esc(t.id)+'</div><h3>'+esc(t.title)+'</h3><div class="pills"><span class="pill">'+esc(t.domain)+'</span><span class="pill">'+esc(t.archetype)+'</span><span class="pill '+String(t.difficulty||"").toLowerCase()+'">'+esc(t.difficulty)+'</span>'+(t.ess!=null?'<span class="pill">ESS '+esc(t.ess)+'</span>':'')+'</div><div class="mini-progress"><i style="width:'+clamp(p.percent||0,0,100)+'%"></i></div><div class="task-foot"><span>'+esc(p.passed)+' / '+esc(p.total)+' checks passed</span><span>v'+esc(t.version)+'</span></div>'+(f.length?'<div class="fail">⚠ '+esc(f.slice(0,2).join(" · "))+'</div>':'')+'</article>'}
function renderBoard(){var ts=filtered();el("visibleCount").textContent=ts.length+" visible task"+(ts.length===1?"":"s");el("board").innerHTML=STAGES.map(function(s){var rows=ts.filter(function(t){return t.stage===s[0]});return'<div class="lane"><div class="lane-head"><b>'+esc(s[1])+'</b><span class="count">'+rows.length+'</span></div><div class="cards">'+(rows.length?rows.map(card).join(""):'<div class="empty">No tasks in this stage</div>')+'</div></div>'}).join("");Array.prototype.forEach.call(document.querySelectorAll(".open"),function(b){b.addEventListener("click",function(){openTask(b.getAttribute("data-task"))})})}
function renderActivity(){var xs=data.activity||[];el("activity").innerHTML=xs.length?xs.map(function(a){return'<div class="activity-item"><div class="activity-type">'+esc(a.type)+'</div><div><b>'+esc(a.title)+'</b><p>'+esc(a.detail||"")+'</p>'+(a.tasks&&a.tasks.length?'<p>'+esc(a.tasks.join(" · "))+'</p>':'')+'</div></div>'}).join(""):'<div class="empty">No activity recorded yet.</div>'}
function renderDomains(){var d=data.domain_counts||{},vs=Object.values(d),m=Math.max.apply(null,vs.length?vs:[1]);el("domainBars").innerHTML=Object.keys(d).sort().map(function(k){return'<div class="domain-row"><span title="'+esc(k)+'">'+esc(k)+'</span><div class="domain-track"><i style="width:'+d[k]/m*100+'%"></i></div><b>'+d[k]+'</b></div>'}).join("")}
function openTask(id){var t=(data.tasks||[]).find(function(x){return x.id===id});if(!t)return;var p=t.pipeline_summary||{passed:0,failed:0,waiting:0,total:17},checks=(t.pipeline||[]).map(function(c,i){return'<div class="check"><div class="check-num">'+String(i+1).padStart(2,"0")+'</div><div><b>'+esc(c.label)+'</b><small>'+esc(c.raw==null?"No fresh evidence yet":c.raw)+'</small></div><span class="state '+esc(c.status)+'">'+esc(c.status)+'</span></div>'}).join(""),fails=(t.failure_codes||[]).length?'<div class="failure-box"><b>Current failure / repair reason</b><br>'+esc(t.failure_codes.join(" · "))+'</div>':'',ung=(t.unresolved_gates||[]).length?'<div class="failure-box" style="background:#fff9ec;border-color:#e9dab8;color:#8c6828"><b>Unresolved gates</b><br>'+esc(t.unresolved_gates.join(" · "))+'</div>':'';el("drawerContent").innerHTML='<div class="drawer-top"><div><div class="did">'+esc(t.id)+'</div><h2>'+esc(t.title)+'</h2><div class="drawer-sub">'+esc(t.domain)+' · '+esc(t.archetype)+(t.subdomain?' · '+esc(t.subdomain):'')+'</div></div><button class="close" id="closeDrawer">×</button></div><div class="drawer-stats"><div class="drawer-stat"><b>'+esc(label(t.stage))+'</b><span>Current stage</span></div><div class="drawer-stat"><b>'+esc(t.difficulty)+'</b><span>Difficulty</span></div><div class="drawer-stat"><b>'+(t.ess==null?'—':esc(t.ess))+'</b><span>ESS</span></div><div class="drawer-stat"><b>'+(t.structural_score==null?'—':esc(t.structural_score)+'/20')+'</b><span>Structural</span></div></div>'+fails+ung+'<div class="pipeline-title"><b>17-stage validation pipeline</b><span>'+p.passed+' passed · '+p.failed+' failed · '+p.waiting+' waiting</span></div><div class="checks">'+checks+'</div><div class="pipeline-title"><b>Capabilities</b><span>v'+esc(t.version)+'</span></div><div class="caps">'+((t.capabilities||[]).map(function(x){return'<span class="cap">'+esc(x)+'</span>'}).join("")||'<span class="cap">Not listed</span>')+'</div>';el("drawer").classList.add("show");el("backdrop").classList.add("show");el("drawer").setAttribute("aria-hidden","false");el("closeDrawer").addEventListener("click",closeDrawer)}
function closeDrawer(){el("drawer").classList.remove("show");el("backdrop").classList.remove("show");el("drawer").setAttribute("aria-hidden","true")}
function render(){if(!data)return;renderMetrics();renderAgents();fillFilters();renderBoard();renderActivity();renderDomains();var dt=new Date(data.generated_at),age=(Date.now()-dt.getTime())/1000;el("freshness").textContent=isNaN(dt)?"Pipeline connected":"Updated "+dt.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})+" · "+(age<90?"live":"stale");el("liveDot").classList.toggle("off",age>180)}
async function load(silent){try{var r=await fetch("status.json?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error();data=await r.json();lastGood=data;render();if(!silent)toast("Pipeline refreshed")}catch(e){if(lastGood){data=lastGood;render()}el("freshness").textContent="Connection retrying…";el("liveDot").classList.add("off")}}
["search","stageFilter","domainFilter","difficultyFilter"].forEach(function(id){el(id).addEventListener(id==="search"?"input":"change",renderBoard)});
el("clearFilters").addEventListener("click",function(){el("search").value="";el("stageFilter").value="";el("domainFilter").value="";el("difficultyFilter").value="";renderBoard()});
el("manualRefresh").addEventListener("click",function(){load(false)});el("backdrop").addEventListener("click",closeDrawer);el("jumpBoard").addEventListener("click",function(){el("pipelineBoard").scrollIntoView({behavior:"smooth"})});document.addEventListener("keydown",function(e){if(e.key==="Escape")closeDrawer()});
load(true);setInterval(function(){load(true)},15000);setInterval(renderAgents,30000);
})();